# Change these first
owner: dohoons # Your GitHub username
repo: upptime # Your GitHub repository name

env:
  NOTIFICATION_SLACK = true
  NOTIFICATION_SLACK_WEBHOOK = true

# Add your sites here
sites:
  - name: dohoons.com
    url: https://dohoons.com

status-website:
  baseUrl: /uptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: dohoons
  introTitle: Status dohoons
  introMessage: Ubiquitous Web
  navbar:
    - title: Status
      href: /uptime
    - title: GitHub
      href: https://github.com/dohoons

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
