# Change these first
owner: dohoons # Your GitHub username
repo: upptime # Your GitHub repository name

# Add your sites here
sites:
  - name: dohoons.com
    url: https://dohoons.com

status-website:
  baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: dohoons
  introTitle: Status dohoons
  introMessage: Ubiquitous Web
  navbar:
    - title: Status
      href: /upptime
    - title: GitHub
      href: https://github.com/dohoons

# notifications:
#   NOTIFICATION_SLACK_STRATEGY: roundrobin
#   NOTIFICATION_SLACK: true
#   NOTIFICATION_SLACK_WEBHOOK: true
#   NOTIFICATION_SLACK_WEBHOOK_URL: ${{ secrets.NOTIFICATION_SLACK_WEBHOOK_URL }}
